Redirect error messages to stderr, fix few exit codes to indicate failure

diff --git a/lib-bump-check b/lib-bump-check
--- a/lib-bump-check
+++ b/lib-bump-check
@@ -32,7 +32,7 @@ check_package() {
 }
 
 display_usage() {
-	<< EOF cat
+	<< EOF >&2 cat
 Usage: lib-bump-check [-b] [-h] [-j jobs] [-r pkgname]
 
     -b - disable check for library newer version
@@ -41,7 +41,7 @@ Usage: lib-bump-check [-b] [-h] [-j jobs] [-r pkgname]
     -r - check only packages that depend on pkgname
 
 EOF
-	exit
+	exit 1
 }
 
 exit_clean() {
@@ -124,7 +124,7 @@ while getopts "bj:hr:" option; do
 		[1-9])
 			JOBS="${OPTARG}" ;;
 		*)
-			echo "-j requires numerical argument"
+			echo "-j requires numerical argument" >&2
 			exit 1
 		esac ;;
 	r)
@@ -136,12 +136,12 @@ while getopts "bj:hr:" option; do
 done
 
 if [ ! -x "${LOCALBASE}/sbin/portmaster" ]; then
-	echo "This script requires portmaster"
+	echo "This script requires portmaster" >&2
 	exit 1
 fi
 
 if [ "$(id -u)" != "0" ]; then
-	echo "You need root privileges to rebuild packages"
+	echo "You need root privileges to rebuild packages" >&2
 	exit 1
 fi
 
@@ -166,7 +166,7 @@ readonly TMP_STALE="$(mktemp -t lbc-stale)"
 readonly TMP_BAD="$(mktemp -t lbc-bad)"
 
 if [ -z "${TMP_SEM}" -o -z "${TMP_STALE}" -o -z "${TMP_BAD}" ]; then
-	echo "Failed to create temporary files"
+	echo "Failed to create temporary files" >&2
 	exit_clean 1
 fi
 
diff --git a/pcommit b/pcommit
--- a/pcommit
+++ b/pcommit
@@ -48,7 +48,7 @@ dir_cache_add() {
 }
 
 display_usage() {
-	<< EOF cat
+	<< EOF >&2 cat
 Usage: pcommit [-c|-e|-h|-n]
 
     -c - clean temp files only
@@ -57,7 +57,7 @@ Usage: pcommit [-c|-e|-h|-n]
     -n - non-interactive mode
 
 EOF
-	exit
+	exit 1
 }
 
 file_add() {
@@ -69,7 +69,7 @@ file_add() {
 		[ ${non_interactive} -eq 0 ] || echo "===> Adding file ${file}"
 		${PSVN} -q add "${file}"
 		if [ ${?} -ne 0 ]; then
-			echo "===> File addition failed"
+			echo "===> File addition failed" >&2
 			pcommit_exit 1
 		fi
 
@@ -100,7 +100,7 @@ file_remove() {
 		[ ${non_interactive} -eq 0 ] || echo "===> Removing ${n_kind} ${file}"
 		${PSVN} -q --force rm "${file}"
 		if [ ${?} -ne 0 ]; then
-			echo "===> File removal failed"
+			echo "===> File removal failed" >&2
 			pcommit_exit 1
 		fi
 		
@@ -188,9 +188,9 @@ if [ -n "${wrk_dirs}" ]; then
 		ret="$(make ${make_args} clean 2>/dev/null)"
 		if [ -n "$(echo ${ret} | grep 'not writable')" ]; then
 			if [ ${depth} -ne 2 ]; then
-				echo "===> Failed to 'make clean' in ${wdir%%/work}"
+				echo "===> Failed to 'make clean' in ${wdir%%/work}" >&2
 			else
-				echo "===> Failed to 'make clean'"
+				echo "===> Failed to 'make clean'" >&2
 			fi
 			exit 1
 		fi
@@ -199,7 +199,7 @@ fi
 
 rej_files="$(find . -name "*.rej" -maxdepth ${depth} | sed 's|^./||g')"
 if [ -n "${rej_files}" ]; then
-	echo "===> Found rejected patch files"
+	echo "===> Found rejected patch files" >&2
 	echo ${rej_files} | tr ' ' '\n'
 	exit 1
 fi
@@ -229,14 +229,14 @@ fi
 
 tempfile="$(mktemp -t pcommit)"
 if [ -z "${tempfile}" ]; then
-	echo "===> Failed to create temporary file"
+	echo "===> Failed to create temporary file" >&2
 	exit 1
 fi
 trap 'pcommit_exit 1' int
 
 ${PSVN} --show-updates status > ${tempfile}
 if [ ${?} -ne 0 ]; then
-	echo "===> '${PSVN} status' failed"
+	echo "===> '${PSVN} status' failed" >&2
 	pcommit_exit 1 
 fi
 
diff --git a/pdiff b/pdiff
--- a/pdiff
+++ b/pdiff
@@ -4,7 +4,7 @@ PORTSDIR="${PORTSDIR:-/usr/ports}"
 [ -d "${PORTSDIR}" ] || \
 	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
 if [ ! -d "${PORTSDIR}" ]; then
-	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable"
+	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
 	exit 1
 fi
 
@@ -18,7 +18,7 @@ portdir_clean() {
 	if [ -d "${dir}/work" ]; then
 		cd "${dir}"
 		if [ -n "$(make clean 2>/dev/null | grep 'not writable')" ]; then
-			echo "===> Failed to make clean in ${dir}"
+			echo "===> Failed to make clean in ${dir}" >&2
 			exit 1
 		fi
 	fi
@@ -26,7 +26,7 @@ portdir_clean() {
 }
 
 if [ -z "${port}" -o -z "${category}" ]; then
-	echo "===> This is not port directory"
+	echo "===> This is not port directory" >&2
 	exit 1
 fi
 
@@ -38,7 +38,7 @@ portdir_clean "${PWD}"
 if [ -d "${old_ver_dir}" ]; then
 	portdir_clean "${old_ver_dir}"
 else
-	echo "===> Orginal port directory does not exist"
+	echo "===> Orginal port directory does not exist" >&2
 	exit 1
 fi
 
diff --git a/pfind b/pfind
--- a/pfind
+++ b/pfind
@@ -4,12 +4,12 @@ PORTSDIR=${PORTSDIR:-/usr/ports}
 [ -d "${PORTSDIR}" ] || \
 	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
 if [ ! -d "${PORTSDIR}" ]; then
-	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable"
+	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
 	exit 1
 fi
 
 display_usage() {
-	<< EOF cat
+	<< EOF >&2 cat
 Usage: pfind [-c category] [-h] [-m maintainer] [-n name] [-s string]
 
     -c - port category
@@ -19,14 +19,14 @@ Usage: pfind [-c category] [-h] [-m maintainer] [-n name] [-s string]
     -s - string to find in port's Makefile
 
 EOF
-	exit
+	exit 1
 }
 
 while getopts "c:hm:n:s:" option; do
 	case ${option} in
 	c)
 		if [ ! -d ${PORTSDIR}/${OPTARG} ]; then
-			echo "No such category: ${OPTARG}"
+			echo "No such category: ${OPTARG}" >&2
 			exit 1
 		fi
 		category="${OPTARG}/" ;;
diff --git a/pkg-cutter b/pkg-cutter
--- a/pkg-cutter
+++ b/pkg-cutter
@@ -10,7 +10,7 @@ rm_count=0
 sel_status="off"
 
 display_usage() {
-	<< EOF cat
+	<< EOF >&2 cat
 Usage: pkg-cutter [-h|-x]
        pkg-cutter [-o] [-y]
 
@@ -20,13 +20,13 @@ Usage: pkg-cutter [-h|-x]
     -y - assume yes when there are new leaf packages
 
 EOF
-	exit
+	exit 1
 }
 
 mktmp() {
 	local tmp="$(mktemp -t pkg-cutter)"
 	if [ -z "${tmp}" ]; then
-		echo "===> Failed to create temporary file"
+		echo "===> Failed to create temporary file" >&2
 		exit 1
 	fi
 	echo ${tmp}
@@ -100,7 +100,7 @@ while getopts "hoxy" option; do
 done
 
 if [ "$(id -u)" != "0" ]; then
-	echo "You need root privileges to remove packages"
+	echo "You need root privileges to remove packages" >&2
 	exit 1
 fi
 
diff --git a/plist-sort b/plist-sort
--- a/plist-sort
+++ b/plist-sort
@@ -5,14 +5,14 @@ readonly PREFIX="$(make -V PREFIX 2>/dev/null)"
 plist_file="${1}"
 
 if [ -z "${PKGNAME}" -o -z "${PREFIX}" ]; then
-	echo "===> This is not port directory"
+	echo "===> This is not port directory" >&2
 	exit 1
 fi
 
 [ -n "${plist_file}" ] || plist_file=$(make -V PLIST)
 
 if [ ! -f "${plist_file}" ]; then
-	echo "===> Plist file was not found: ${plist_file}"
+	echo "===> Plist file was not found: ${plist_file}" >&2
 	exit 1
 fi
 
diff --git a/plist-update b/plist-update
--- a/plist-update
+++ b/plist-update
@@ -5,18 +5,18 @@ readonly PKGNAME="$(make -V PKGNAME 2>/dev/null)"
 readonly PLIST="$(make -V PLIST 2>/dev/null)"
 
 if [ -z "$(whereis -bq plist-sort)" ]; then
-	echo "===> Required script plist-sort not found"
+	echo "===> Required script plist-sort not found" >&2
 	exit 1
 fi
 
 if [ -z "${PKGNAME}" ]; then
-	echo "===> This is not port directory"
+	echo "===> This is not port directory" >&2
 	exit 1
 fi
 
 tempfile="$(mktemp -t tb-plist-update)"
 if [ -z "${tempfile}" ]; then
-	echo "===> Failed to create temporary file"
+	echo "===> Failed to create temporary file" >&2
 	exit 1
 fi
 [ -f pkg-plist ] && plist_out="pkg-plist.new" || plist_out="pkg-plist"
diff --git a/plog b/plog
--- a/plog
+++ b/plog
@@ -6,7 +6,7 @@ readonly POUDRIERE_DIR="${POUDRIERE_DIR:-/usr/local/poudriere}"
 readonly POUDRIERE_PORTS="${POUDRIERE_PORTS:-${POUDRIERE_DIR}/ports/default}"
 
 if [ ! -d "${POUDRIERE_PORTS}" ]; then
-	echo "Ports directory not found: ${POUDRIERE_PORTS}, try setting POUDRIERE_PORTS variable"
+	echo "Ports directory not found: ${POUDRIERE_PORTS}, try setting POUDRIERE_PORTS variable" >&2
 	exit 1
 fi
 
@@ -15,14 +15,14 @@ port="${2}"
 jail="${3}"
 
 display_usage() {
-	<< EOF cat
+	<< EOF >&2 cat
 Usage: plog <send|show> [category/port] [jailname]
 
    send - scp(1) build log to freefall
    show - see build log
 
 EOF
-	exit
+	exit 1
 }
 
 poudriere_jails() {
@@ -33,13 +33,13 @@ poudriere_jails() {
 
 [ -n "${port}" ] || port="."
 if [ "${port}" != "." -a ! -d "${POUDRIERE_PORTS}/${port}" ]; then
-	printf "${POUDRIERE_PORTS}/${port}: no such port found\n\n"
+	printf "${POUDRIERE_PORTS}/${port}: no such port found\n\n" >&2
 	display_usage
 fi
 
 if [ -n "${jail}" ]; then
 	if [ -z "$(poudriere_jails | grep ${jail})" ]; then
-		printf "${jail}: no such poudriere jail\n\n"
+		printf "${jail}: no such poudriere jail\n\n" >&2
 		display_usage
 	fi
 fi
@@ -50,7 +50,7 @@ readonly PKGBASE="$(make -V PKGBASE 2>/dev/null)"
 readonly PKGVERSION="$(make -V PKGVERSION 2>/dev/null)"
 
 if [ -z "${PKGBASE}" ]; then
-	echo "===> This is not port directory"
+	echo "===> This is not port directory" >&2
 	exit 1
 fi
 
@@ -66,14 +66,14 @@ if [ -z "${jail}" ]; then
 	done
 	
 	if [ -z "${jail}" ]; then
-		echo "===> Could not find any build logs for ${PKGBASE}-${PKGVERSION}"
+		echo "===> Could not find any build logs for ${PKGBASE}-${PKGVERSION}" >&2
 		exit 1
 	fi
 fi
 
 logfile="${logdir}/${jail}-${ports_tree}.log"
 if [ ! -f "${logfile}" ]; then
-	echo "===> Logfile ${logfile} does not exist"
+	echo "===> Logfile ${logfile} does not exist" >&2
 	exit 1
 fi
 
diff --git a/rports b/rports
--- a/rports
+++ b/rports
@@ -4,14 +4,14 @@ readonly PSVN="${PSVN:-svn}"
 readonly RPORTSDIR="${RPORTSDIR:-${HOME}/redports}"
 
 display_usage() {
-	<< EOF cat
+	<< EOF >&2 cat
 Usage: rports [-h|-n] [portdir]
 
     -h - show this help
     -n - non-interactive mode
 
 EOF
-	exit
+	exit 1
 }
 
 while getopts "hn" option; do
@@ -28,18 +28,18 @@ shift $((OPTIND-1))
 
 readonly PORTPATH="$(realpath -q "${1}")"
 if [ -z "${PORTPATH}" ]; then
-	echo "===> Port directory (${1}) does not exist"
+	echo "===> Port directory (${1}) does not exist" >&2
 	exit 1
 fi
 
 if [ ! -d "${RPORTSDIR}" ]; then
-	echo "===> Redports checkout directory (${RPORTSDIR}) does not exist"
-       	echo "===> Try setting RPORTSDIR variable"
+	echo "===> Redports checkout directory (${RPORTSDIR}) does not exist" >&2
+	echo "===> Try setting RPORTSDIR variable" >&2
 	exit 1
 fi
 
 if [ -z "$(whereis -bq pcommit)" ]; then
-	echo "===> pcommit script not found in your PATH"
+	echo "===> pcommit script not found in your PATH" >&2
 	exit 1
 fi
 
@@ -48,7 +48,7 @@ cd "${PORTPATH}"
 
 category="$(make -V CATEGORIES | awk '{ print $1 }')"
 if [ -z "${category}" ]; then
-	echo "===> Can't get port's category"
+	echo "===> Can't get port's category" >&2
 	exit 1
 fi
 port="$(basename ${PWD})"
@@ -95,7 +95,7 @@ done
 
 cd "${RPORTSDIR}/${commit_path}" 
 if [ -z "$(${PSVN} info | grep '^URL:.*redports.org')" ]; then
-	echo "===> Not a redports.org checkout, check svn info"
+	echo "===> Not a redports.org checkout, check svn info" >&2
 	exit 1
 fi
 
diff --git a/tbuilder b/tbuilder
--- a/tbuilder
+++ b/tbuilder
@@ -6,7 +6,7 @@ readonly POUDRIERE_DIR="${POUDRIERE_DIR:-/usr/local/poudriere}"
 readonly POUDRIERE_PORTS="${POUDRIERE_PORTS:-${POUDRIERE_DIR}/ports/default}"
 
 if [ ! -d "${POUDRIERE_PORTS}" ]; then
-	echo "Ports directory not found: ${POUDRIERE_PORTS}, try setting POUDRIERE_PORTS variable"
+	echo "Ports directory not found: ${POUDRIERE_PORTS}, try setting POUDRIERE_PORTS variable" >&2
 	exit 1
 fi
 
@@ -15,7 +15,7 @@ readonly query="${2}"
 readonly build="${3:-none}"
 
 display_usage() {
-	<< EOF cat
+	<< EOF >&2 cat
 Usage: tbuilder <command> <query> [jail_name] [poudriere testport args]
 
  command: bdeps - build ports having certain build dependency
@@ -34,7 +34,7 @@ Usage: tbuilder <command> <query> [jail_name] [poudriere testport args]
  jail_name: poudriere jail name or 'all' for all available jails
 
 EOF
-	exit
+	exit 1
 }
 
 poudriere_jails() {
@@ -67,7 +67,7 @@ poudriere_test_build() {
 if [ "${build}" != "none" -a "${build}" != "all" \
 	-a -z "$(poudriere_jails | grep ${build})" ]
 then
-	printf "${build}: no such poudriere jail\n\n"
+	printf "${build}: no such poudriere jail\n\n" >&2
 	display_usage
 fi
 
@@ -81,7 +81,7 @@ bdeps)
 	ports="$(portsearch -b ${query} | grep Path: | cut -f 4- -d '/')" ;;
 file)
 	if [ ! -f "${query}" ]; then
-		echo "File ${query} does not exists"
+		echo "File ${query} does not exists" >&2
 		exit 1
 	fi
 	ports="$(cat "${query}")" ;;
@@ -91,7 +91,7 @@ grep)
 		| sed -E 's;(\./|/Makefile);;g')" ;;
 ldeps)
 	if [ ! -d "${POUDRIERE_PORTS}/${query}" ]; then
-		printf "${POUDRIERE_PORTS}/${query}: port directory does not exists\n\n"
+		printf "${POUDRIERE_PORTS}/${query}: port directory does not exists\n\n" >&2
 		display_usage
 	fi
 	tmp="$(cd ${POUDRIERE_PORTS} && find . -name "Makefile*" -exec grep -q \
@@ -128,7 +128,7 @@ match)
 	ports="$(portsearch -n ${query} | grep Path: | cut -f 4- -d '/')" ;;
 name)
 	if [ "${query}" != "." -a ! -d "${POUDRIERE_PORTS}/${query}" ]; then
-		printf "${POUDRIERE_PORTS}/${query}: port directory does not exists\n\n"
+		printf "${POUDRIERE_PORTS}/${query}: port directory does not exists\n\n" >&2
 		display_usage
 	fi
 	ports="${query}"
diff --git a/upgrade-base b/upgrade-base
--- a/upgrade-base
+++ b/upgrade-base
@@ -23,7 +23,7 @@ ask_yesno() {
 }
 
 display_usage() {
-	<< EOF cat
+	<< EOF >&2 cat
 Usage: upgrade-base [-c|-h|-s]
 
     -c - do not clean tree before build (NO_CLEAN=yes)
@@ -31,7 +31,7 @@ Usage: upgrade-base [-c|-h|-s]
     -s - reset status and begin from start
 
 EOF
-	exit
+	exit 1
 }
 
 # $1 make target
@@ -39,7 +39,7 @@ EOF
 exec_cmd() {
 	${1}
 	if [ ${?} -ne 0 ]; then
-		echo "===> '${1}' failed"
+		echo "===> '${1}' failed" >&2
 		exit 1
 	fi
 	save_state "${2}"
@@ -61,7 +61,7 @@ main_loop() {
 		l_entry=$(last_updating_entry)
 		${PSVN} update
 		if [ ${?} -ne 0 ]; then
-			echo "===> Updating of source tree failed"
+			echo "===> Updating of source tree failed" >&2
 			exit 1
 		fi
 
@@ -123,7 +123,7 @@ main_loop() {
 		printf "\n===> You need to restart computer again.\n\n"
 		exit 0 ;;
 	*)
-		echo "===> Garbage in ${CONF_FILE}, try upgrade-base -s"
+		echo "===> Garbage in ${CONF_FILE}, try upgrade-base -s" >&2
 		exit 1
 	esac
 	main_loop	
@@ -140,7 +140,7 @@ PORTSDIR=${PORTSDIR:-/usr/ports}
 [ -d "${PORTSDIR}" ] || \
 	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
 if [ ! -d "${PORTSDIR}" ]; then
-	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable"
+	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
 	exit 1
 fi
 
diff --git a/upgrade-ports b/upgrade-ports
--- a/upgrade-ports
+++ b/upgrade-ports
@@ -9,7 +9,7 @@ PORTSDIR=${PORTSDIR:-/usr/ports}
 [ -d "${PORTSDIR}" ] || \
 	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
 if [ ! -d "${PORTSDIR}" ]; then
-	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable"
+	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
 	exit 1
 fi
 
@@ -33,7 +33,7 @@ ask_yesno() {
 }
 
 display_usage() {
-	<< EOF cat
+	<< EOF >&2 cat
 Usage: upgrade-ports [-h|-w|-y]
 
     -h - show this help
@@ -41,7 +41,7 @@ Usage: upgrade-ports [-h|-w|-y]
     -y - answer yes to all questions
 
 EOF
-	exit
+	exit 1
 }
 
 get_entry_dates() {
@@ -121,12 +121,12 @@ done
 
 
 if [ -z "$(whereis -bq sudo)" ]; then
-	echo "===> sudo not found"
+	echo "===> sudo not found" >&2
 	upgrade_exit 1 "" ${wait_for_key}
 fi
 
 if [ -z "$(whereis -bq portmaster)" ]; then
-	echo "===> portmaster not found"
+	echo "===> portmaster not found" >&2
 	upgrade_exit 1 "" ${wait_for_key}
 fi
 
@@ -146,7 +146,7 @@ fi
 
 sudo /usr/sbin/portsnap fetch update
 if [ ${?} -ne 0 ]; then
-	echo "===> Ports tree update failed"
+	echo "===> Ports tree update failed" >&2
 	upgrade_exit 1 "" ${wait_for_key}
 fi
 
@@ -155,7 +155,7 @@ last_upd="$(get_entry_dates | head -n 1)"
 if [ ${last_read} -lt ${last_upd} ]; then
 	tmpfile="$(mktemp -t upgrade-ports)"
 	if [ -z "${tmpfile}" ]; then
-		echo "===> Failed to create temporary file"
+		echo "===> Failed to create temporary file" >&2
 		upgrade_exit 1 "" ${wait_for_key}
 	fi
 
@@ -183,7 +183,7 @@ if [ ${last_read} -lt ${last_upd} ]; then
 				IFS=$'\n'
 				
 				if [ ${ret} -ne 0 ]; then
-					echo "===> Upgrade command '${cmd}' failed"
+					echo "===> Upgrade command '${cmd}' failed" >&2
 					upgrade_exit ${ret} "${entry_prev}" ${wait_for_key}
 				fi
 			fi
