Use common prefix for scripts messages

diff --git a/lib-bump-check b/lib-bump-check
--- a/lib-bump-check
+++ b/lib-bump-check
@@ -124,7 +124,7 @@ while getopts "bj:hr:" option; do
 		[1-9])
 			JOBS="${OPTARG}" ;;
 		*)
-			echo "-j requires numerical argument" >&2
+			echo "===> -j requires numerical argument" >&2
 			exit 1
 		esac ;;
 	r)
@@ -137,12 +137,12 @@ done
 
 which portmaster > /dev/null
 if [ ${?} -ne 0 ]; then
-	echo "This script requires portmaster" >&2
+	echo "===> This script requires portmaster" >&2
 	exit 1
 fi
 
 if [ "$(id -u)" != "0" ]; then
-	echo "You need root privileges to rebuild packages" >&2
+	echo "===> You need root privileges to rebuild packages" >&2
 	exit 1
 fi
 
@@ -156,7 +156,7 @@ fi
 
 pkg_all="$(echo ${packages} | wc -w)"
 if [ ${pkg_all} -eq 0 ]; then
-	echo "No packages to check found"
+	echo "===> No packages to check found"
 	exit
 fi
 
@@ -167,7 +167,7 @@ readonly TMP_STALE="$(mktemp -t lbc-stale)"
 readonly TMP_BAD="$(mktemp -t lbc-bad)"
 
 if [ -z "${TMP_SEM}" -o -z "${TMP_STALE}" -o -z "${TMP_BAD}" ]; then
-	echo "Failed to create temporary files" >&2
+	echo "===> Failed to create temporary files" >&2
 	exit_clean 1
 fi
 
@@ -177,7 +177,7 @@ if [ -f "${IGNORE_FILE}" ]; then
 	n=0
 	pkg_ignore="$(grep -v '^#' "${IGNORE_FILE}")"
 	for pkg in ${pkg_ignore}; do n=$((n+1)); done
-	[ ${n} -eq 0 ] || echo "Read ${IGNORE_FILE}, ${n} entries found"
+	[ ${n} -eq 0 ] || echo "===> Read ${IGNORE_FILE}, ${n} entries found"
 fi
 
 lockf -k "${TMP_SEM}" echo ${JOBS} > "${TMP_SEM}"
@@ -215,11 +215,11 @@ fi
 
 pkg_stale="$(cat ${TMP_STALE})"
 if [ -z "${pkg_stale}" ]; then
-	printf "No packages linked to stale libs found\n\n"
+	printf "===> No packages linked to stale libs found\n\n"
 	exit_clean 0
 fi
 
-printf "Following packages are linked to stale libs:\n\n"
+printf "===> Following packages are linked to stale libs:\n\n"
 for pkg in ${pkg_stale}; do
 	pkg_re="${pkg_re} ${pkg%%@*}"
 	echo "   ${pkg%%@*} => ${pkg#*@}" | sed 's|@| |g'
diff --git a/pdiff b/pdiff
--- a/pdiff
+++ b/pdiff
@@ -4,7 +4,7 @@ PORTSDIR="${PORTSDIR:-/usr/ports}"
 [ -d "${PORTSDIR}" ] || \
 	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
 if [ ! -d "${PORTSDIR}" ]; then
-	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
+	echo "===> Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
 	exit 1
 fi
 
diff --git a/pfind b/pfind
--- a/pfind
+++ b/pfind
@@ -50,17 +50,17 @@ done
 [ -d "${PORTSDIR}" ] || \
 	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
 if [ ! -d "${PORTSDIR}" ]; then
-	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
+	echo "===> Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
 	exit 1
 fi
 
 if [ -n "${category}" -a ! -d ${PORTSDIR}/${category} ]; then
-	echo "No such category: ${category}" >&2
+	echo "===> No such category: ${category}" >&2
 	exit 1
 fi
 
 if [ -n "${master}" -a ! -d ${PORTSDIR}/${master} ]; then
-	echo "No such port: ${PORTSDIR}/${master}" >&2
+	echo "===> No such port: ${PORTSDIR}/${master}" >&2
 	exit 1
 fi
 
diff --git a/plog b/plog
--- a/plog
+++ b/plog
@@ -27,19 +27,19 @@ poudriere_jails() {
 [ "${cmd}" != "send" -a "${cmd}" != "show" ] && display_usage
 
 if [ ! -d "${POUDRIERE_PORTS}" ]; then
-	echo "Ports directory not found: ${POUDRIERE_PORTS}, try setting POUDRIERE_PORTS variable" >&2
+	echo "===> Ports directory not found: ${POUDRIERE_PORTS}, try setting POUDRIERE_PORTS variable" >&2
 	exit 1
 fi
 
 [ -n "${port}" ] || port="."
 if [ "${port}" != "." -a ! -d "${POUDRIERE_PORTS}/${port}" ]; then
-	printf "${POUDRIERE_PORTS}/${port}: no such port found\n\n" >&2
+	printf "===> ${POUDRIERE_PORTS}/${port}: no such port found\n\n" >&2
 	display_usage
 fi
 
 if [ -n "${jail}" ]; then
 	if [ -z "$(poudriere_jails | grep ${jail})" ]; then
-		printf "${jail}: no such poudriere jail\n\n" >&2
+		printf "===> ${jail}: no such poudriere jail\n\n" >&2
 		display_usage
 	fi
 fi
diff --git a/tbuilder b/tbuilder
--- a/tbuilder
+++ b/tbuilder
@@ -21,7 +21,7 @@ check_portname() {
 	fi
 
 	if [ ! -d "${POUDRIERE_PORTS}/${port}" ]; then
-		printf "${POUDRIERE_PORTS}/${port}: port directory does not exists\n\n" >&2
+		printf "===> ${POUDRIERE_PORTS}/${port}: port directory does not exists\n\n" >&2
 		display_usage
 	fi
 
@@ -90,7 +90,7 @@ poudriere_test_build() {
 if [ "${build}" != "none" -a "${build}" != "all" \
 	-a -z "$(poudriere_jails | grep ${build})" ]
 then
-	printf "${build}: no such poudriere jail\n\n" >&2
+	printf "===> ${build}: no such poudriere jail\n\n" >&2
 	display_usage
 fi
 
@@ -100,7 +100,7 @@ if [ -n "${4}" ]; then
 fi
 
 if [ ! -d "${POUDRIERE_PORTS}" ]; then
-	echo "Ports directory not found: ${POUDRIERE_PORTS}, try setting POUDRIERE_PORTS variable" >&2
+	echo "===> Ports directory not found: ${POUDRIERE_PORTS}, try setting POUDRIERE_PORTS variable" >&2
 	exit 1
 fi
 
@@ -120,7 +120,7 @@ bdeps)
 	ports="$(pfind -b ${query})" ;;
 file)
 	if [ ! -f "${query}" ]; then
-		echo "File ${query} does not exists" >&2
+		echo "===> File ${query} does not exists" >&2
 		exit 1
 	fi
 	ports="$(cat "${query}" | grep -v '^#')" ;;
diff --git a/upgrade-base b/upgrade-base
--- a/upgrade-base
+++ b/upgrade-base
@@ -98,7 +98,7 @@ main_loop() {
 
 			n_entry=$(last_updating_entry)
 			if [ ${n_entry} -gt ${l_entry} ]; then
-				printf "New entries since last upgrade in ${SRCDIR}/UPDATING file:\n\n"
+				printf "===> New entries since last upgrade in ${SRCDIR}/UPDATING file:\n\n"
 				awk -v entry="${l_entry}" '
 				BEGIN { new_entry=0; }
 	
@@ -174,7 +174,7 @@ while getopts "chsu" option; do
 done
 
 if [ "$(id -u)" != "0" ]; then
-	echo "You need root privileges to upgrade base system" >&2
+	echo "===> You need root privileges to upgrade base system" >&2
 	exit 1
 fi
 
@@ -186,7 +186,7 @@ PORTSDIR=${PORTSDIR:-/usr/ports}
 [ -d "${PORTSDIR}" ] || \
 	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
 if [ ! -d "${PORTSDIR}" ]; then
-	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
+	echo "===> Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
 	exit 1
 fi
 make_args="${make_args} PORTSDIR=${PORTSDIR}"
diff --git a/upgrade-ports b/upgrade-ports
--- a/upgrade-ports
+++ b/upgrade-ports
@@ -34,7 +34,7 @@ command_is_relevant() {
 		case ${arg} in
 		"-a")
 			if [ "${upgrade_prg}" = "portmaster" ]; then
-				printf "Skipping upgrade of all packages for now (${*})\n\n"
+				printf "===> Skipping upgrade of all packages for now (${*})\n\n"
 				IFS=${old_IFS}
 				return 1
 			fi
@@ -54,7 +54,7 @@ command_is_relevant() {
 
 			local ret=$(pkg info -e ${arg%:*}; echo ${?})
 			if [ ${ret} -eq 1 ]; then
-				printf "${arg} is not installed, skipping '${*}' command\n\n"
+				printf "===> ${arg} is not installed, skipping '${*}' command\n\n"
 				IFS=${old_IFS}
 				return 1
 			else
@@ -199,7 +199,7 @@ done
 [ -d "${PORTSDIR}" ] || \
 	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
 if [ ! -d "${PORTSDIR}" ]; then
-	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
+	echo "===> Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
 	exit 1
 fi
 
@@ -297,7 +297,7 @@ fi
 ${SUDO} portmaster -a ${portmaster_args}
 [ ${?} -ne 0 ] && upgrade_exit 1 "${last_upd}" ${wait_for_key}
 
-echo "==> Checking packages for missing libraries/dependencies"
+echo "===> Checking packages for missing libraries/dependencies"
 pkgs_rebuild=$(${SUDO} pkg check -dan | awk -v pkg_ignore="${UPGRADE_PORTS_IGNORE}" '
 BEGIN {
 	if ((n = split(pkg_ignore, array, " ")) > 0)
