Convert pclean to git

diff --git a/pclean b/pclean
--- a/pclean
+++ b/pclean
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-readonly PSVN=${PSVN:-svn}
+readonly GIT=${GIT:-git}
 
 echo "===> Removing work dirs..."
 
@@ -33,27 +33,30 @@ if [ "$wrk_dirs" ]; then
 	done
 fi
 
-if ! which "$PSVN" >/dev/null; then
-	echo "===> $PSVN executable not found" >&2
+if ! which "$GIT" >/dev/null; then
+	echo "===> $GIT executable not found" >&2
 	exit 1
 fi
-if $PSVN info >/dev/null 2>&1; then
-	echo "===> Running '$PSVN revert'..."
-	$PSVN revert --depth infinity .
+if $GIT show-branch >/dev/null 2>&1; then
+	echo "===> Running '$GIT restore'..."
+	$GIT restore .
+	echo "===> Running '$GIT clean'..."
+	$GIT clean --force -x
 
-	echo "===> Removing leftover files..."
-	$PSVN status --no-ignore | while read line; do
-		status=$(echo "$line" | awk '{ print $1 }')
-		file=$(echo "$line" | awk ' { print $2 }')
-
-		[ ! "$status" -o ! "$file" ] && continue
-
-		if [ "$status" = "?" -o "$status" = "I" ]; then
-			[ "$file" != "distfiles" ] || continue
-			echo "  $file"
-			rm -rf "$file"
-		else
-			echo "file=$file status=$status"
-		fi
-	done
+# TODO git status is sloooow
+#	echo "===> Removing leftover files..."
+#	$GIT status --short --ignored | while read line; do
+#		status=$(echo "$line" | awk '{ print $1 }')
+#		file=$(echo "$line" | awk ' { print $2 }')
+#
+#		[ ! "$status" -o ! "$file" ] && continue
+#
+#		if [ "$status" = '??' -o "$status" = '!!' ]; then
+#			[ "$file" != "distfiles" ] || continue
+#			echo "  $file"
+#			rm -rf "$file"
+#		else
+#			echo "file=$file status=$status"
+#		fi
+#	done
 fi
