Check if tempfile is created, terminate if otherwise

diff --git a/pcommit b/pcommit
--- a/pcommit
+++ b/pcommit
@@ -211,8 +211,13 @@ if [ -n "$old_files" ]; then
 fi
 [ $clean_only -eq 0 ] || exit
 
-trap 'pcommit_exit 1' int
 tempfile="$(mktemp -t pcommit)"
+if [ -z "$tempfile" ]; then
+	echo "===> Failed to create temporary file"
+	exit 1
+fi
+trap 'pcommit_exit 1' int
+
 $PSVN --show-updates status > $tempfile
 if [ $? -ne 0 ]; then
 	echo "===> '$PSVN status' failed"
diff --git a/pkg-cutter b/pkg-cutter
--- a/pkg-cutter
+++ b/pkg-cutter
@@ -21,6 +21,15 @@ display_usage() {
 	exit
 }
 
+mktmp() {
+	local tmp="$(mktemp -t pkg-cutter)"
+	if [ -z "$tmp" ]; then
+		echo "===> Failed to create temporary file"
+		exit 1
+	fi
+	echo $tmp
+}
+
 number_humanize() {
 	echo "$1" | awk '{
 		bytes = $0;
@@ -56,7 +65,7 @@ update_exclude_list() {
 		count=$((count+1))
 	done
 
-	tmpfile="$(mktemp -t pkg-cutter)"
+	tmpfile="$(mktmp)"
 	echo "--checklist \"Select packages to exclude ($count items):\" \
 		21 70 19 $items" > $tmpfile
 	excluded="$(dialog --stdout --file $tmpfile | sed 's|\"||g')"
@@ -125,7 +134,7 @@ while true; do
 	
 	[ $count -eq 0 ] && break
 
-	[ -z "$tmpfile" ] && tmpfile="$(mktemp -t pkg-cutter)"
+	[ -n "$tmpfile" ] || tmpfile="$(mktmp)"
 	echo "--checklist \"Select packages to delete ($count items):\" \
 		21 70 19 $items" > $tmpfile
 
diff --git a/tb-plist-update b/tb-plist-update
--- a/tb-plist-update
+++ b/tb-plist-update
@@ -11,7 +11,6 @@ tc_cmd() {
 	cd $TBDIR/scripts && $tc_script $*
 }
 
-
 if [ -z "$(whereis -bq plist-sort)" ]; then
 	echo "===> Required script plist-sort not found"
 	exit 1
@@ -44,11 +43,11 @@ else
 fi
 
 tempfile="$(mktemp -t tb-plist-update)"
-if [ -f pkg-plist ]; then
-	plist_out="pkg-plist.new"
-else
-	plist_out="pkg-plist"
+if [ -z "$tempfile" ]; then
+	echo "===> Failed to create temporary file"
+	exit 1
 fi
+[ -f pkg-plist ] && plist_out="pkg-plist.new" || plist_out="pkg-plist"
 
 awk -v prefix="$(make -V PREFIX 2>/dev/null)/" '
 
