Remove ${var} notation when it's not required, NOP change

diff --git a/pcommit b/pcommit
--- a/pcommit
+++ b/pcommit
@@ -15,15 +15,15 @@ removed_dirs=""	# already removed directories
 ask_yesno() {
 	local answer
 
-	[ ${non_interactive} -eq 0 ] || return 0
+	[ $non_interactive -eq 0 ] || return 0
 
 	while true; do
-		echo -n "${1} (y/n)? [y] "
+		echo -n "$1 (y/n)? [y] "
 
 		read answer
-		[ "${answer}" ] || answer="y"
+		[ "$answer" ] || answer="y"
 
-		case ${answer} in
+		case $answer in
 		[Nn])
 			return 1 ;;
 		[Yy])
@@ -35,18 +35,18 @@ ask_yesno() {
 cache_concat() {
 	local str=$(eval echo $"${1}")
 
-	[ ! "${str}" ] && str="${2}" || str="${str} ${2}"
+	[ ! "$str" ] && str="$2" || str="$str $2"
 	setvar ${1} "${str}"
 }
 
 dir_cache_add() {
-	local dir=${1}
+	local dir=$1
 
-	case ${dir_cache} in
-	*${dir}*)
+	case $dir_cache in
+	*$dir*)
 		;;
 	*)
-		cache_concat dir_cache "${dir}"
+		cache_concat dir_cache "$dir"
 	esac
 }
 
@@ -64,21 +64,21 @@ EOF
 }
 
 file_add() {
-	local child file=${1}
+	local child file=$1
 
-	case ${file} in *svn-commit*) return 1 ;; esac
-	[ ${ignore_empty} -eq 1 -a ! -s "${file}" ] && return 1
+	case $file in *svn-commit*) return 1 ;; esac
+	[ $ignore_empty -eq 1 -a ! -s "$file" ] && return 1
 
-	if ask_yesno "Add file ${file}"; then
-		[ ${non_interactive} -eq 0 ] || echo "===> Adding file ${file}"
-		if ! ${PSVN} -q add "${file}"; then
+	if ask_yesno "Add file $file"; then
+		[ $non_interactive -eq 0 ] || echo "===> Adding file $file"
+		if ! $PSVN -q add "$file"; then
 			echo "===> File addition failed" >&2
 			pcommit_exit 1
 		fi
 
-		if [ -d "${file}" ]; then
-			for child in $(ls "${file}"); do
-				file_set_props "${file}/${child}"
+		if [ -d "$file" ]; then
+			for child in $(ls "$file"); do
+				file_set_props "$file/$child"
 			done
 		fi
 		return 0
@@ -88,80 +88,80 @@ file_add() {
 }
 
 file_remove() {
-	local file=${1}
-	local n_kind=$(${PSVN} info "${1}"|awk '/^Node Kind/ { print $3 }')
+	local file=$1
+	local n_kind=$($PSVN info "$1"|awk '/^Node Kind/ { print $3 }')
 
-	if [ "${n_kind}" = "file" ]; then
-		for dir in ${removed_dirs}; do
+	if [ "$n_kind" = "file" ]; then
+		for dir in $removed_dirs; do
 			case $file in $dir/*)
 				return 0
 			esac
 		done
 	fi
 
-	if ask_yesno "Remove ${n_kind} ${file}"; then
-		[ ${non_interactive} -eq 0 ] || echo "===> Removing ${n_kind} ${file}"
-		if ! ${PSVN} -q --force rm "${file}"; then
+	if ask_yesno "Remove $n_kind $file"; then
+		[ $non_interactive -eq 0 ] || echo "===> Removing $n_kind $file"
+		if ! $PSVN -q --force rm "$file"; then
 			echo "===> File removal failed" >&2
 			pcommit_exit 1
 		fi
 
-		if [ "${n_kind}" = "file" ]; then
-			case ${file} in *files/*|*scripts/*)
-				dir_cache_add "$(dirname "${file}")"
+		if [ "$n_kind" = "file" ]; then
+			case $file in *files/*|*scripts/*)
+				dir_cache_add "$(dirname "$file")"
 			esac
 		else
-			cache_concat removed_dirs "${file}"
+			cache_concat removed_dirs "$file"
 		fi
 		return 0
 	else
-		[ "${n_kind}" = "file" ] &&
-			cache_concat dir_cache_ignore "$(dirname "${file}")"
+		[ "$n_kind" = "file" ] &&
+			cache_concat dir_cache_ignore "$(dirname "$file")"
 		return 1
 	fi
 }
 
 file_set_props() {
-	local file=${1}
+	local file=$1
 
-	[ -d "${file}" -o ! -e "${file}" ] && return 1
+	[ -d "$file" -o ! -e "$file" ] && return 1
 
-	case $(egrep -- '\$FreeBSD\$|\$[BDFSer]+:' "${file}" >/dev/null || echo ${?}) in
+	case $(egrep -- '\$FreeBSD\$|\$[BDFSer]+:' "$file" >/dev/null || echo $?) in
 	"")	# matched pattern
-		${PSVN} -q -- propset svn:keywords "FreeBSD=%H" "${file}"
-		${PSVN} -q -- propdel fbsd:nokeywords "${file}" ;;
+		$PSVN -q -- propset svn:keywords "FreeBSD=%H" "$file"
+		$PSVN -q -- propdel fbsd:nokeywords "$file" ;;
 	1)	# no match
-		${PSVN} -q -- propset fbsd:nokeywords yes "${file}"
-		${PSVN} -q -- propdel svn:keywords "${file}" ;;
+		$PSVN -q -- propset fbsd:nokeywords yes "$file"
+		$PSVN -q -- propdel svn:keywords "$file" ;;
 	esac
 
 	[ "${_file##/*}" != "bsd.port.mk" ] &&
-		${PSVN} -q -- propset svn:eol-style native "${file}"
-	${PSVN} -q -- propset svn:mime-type text/plain "${file}"
-	${PSVN} -q -- propdel cvs2svn:cvs-rev "${file}"
+		$PSVN -q -- propset svn:eol-style native "$file"
+	$PSVN -q -- propset svn:mime-type text/plain "$file"
+	$PSVN -q -- propdel cvs2svn:cvs-rev "$file"
 }
 
 pcommit_exit() {
-	[ ! "${tempfile}" ] || rm -f ${tempfile}
-	exit ${1}
+	[ ! "$tempfile" ] || rm -f $tempfile
+	exit $1
 }
 
 remove_empty_dirs() {
 	local dir
 
-	for dir in ${dir_cache}; do
-		[ -d ${dir} ] || continue
-		case ${dir_cache_ignore} in *${dir}*) continue ;; esac
+	for dir in $dir_cache; do
+		[ -d $dir ] || continue
+		case $dir_cache_ignore in *$dir*) continue ;; esac
 
-		if [ ! "$(ls ${dir} 2>&1)" ]; then
-			echo "===> Removing empty directory ${dir}"
-			${PSVN} -q rm ${dir}
+		if [ ! "$(ls $dir 2>&1)" ]; then
+			echo "===> Removing empty directory $dir"
+			$PSVN -q rm $dir
 		fi
 	done
 }
 
 while getopts "cehn" option; do
-	case ${option} in
+	case $option in
 	c)
 		clean_only=1 ;;
 	e)
@@ -180,9 +180,9 @@ else
 fi
 
 wrk_dirs=$(find . -name work -type d -depth $((depth-1)) | sed 's|^./||g')
-if [ "${wrk_dirs}" ]; then
-	for wdir in ${wrk_dirs}; do
-		if [ ${depth} -ne 2 ]; then
+if [ "$wrk_dirs" ]; then
+	for wdir in $wrk_dirs; do
+		if [ $depth -ne 2 ]; then
 			echo "===> Running 'make clean' in ${wdir%%/work}"
 			make_args="-C ${wdir%%/work}"
 		else
@@ -190,9 +190,9 @@ if [ "${wrk_dirs}" ]; then
 			make_args=""
 		fi
 
-		ret=$(make ${make_args} clean 2>/dev/null)
-		if [ "$(echo ${ret} | grep 'not writable')" ]; then
-			if [ ${depth} -ne 2 ]; then
+		ret=$(make $make_args clean 2>/dev/null)
+		if [ "$(echo $ret | grep 'not writable')" ]; then
+			if [ $depth -ne 2 ]; then
 				echo "===> Failed to 'make clean' in ${wdir%%/work}" >&2
 			else
 				echo "===> Failed to 'make clean'" >&2
@@ -202,52 +202,52 @@ if [ "${wrk_dirs}" ]; then
 	done
 fi
 
-rej_files=$(find . -name "*.rej" -maxdepth ${depth} | sed 's|^./||g')
-if [ "${rej_files}" ]; then
+rej_files=$(find . -name "*.rej" -maxdepth $depth | sed 's|^./||g')
+if [ "$rej_files" ]; then
 	echo "===> Found rejected patch files" >&2
-	echo ${rej_files} | tr ' ' '\n'
+	echo $rej_files | tr ' ' '\n'
 	exit 1
 fi
 
 old_files=$(find -E . \( -name "*.orig" -or -name "svn-commit.*" \) \
-	! -regex '.*(\.svn|work)/.*' -delete -print -maxdepth ${depth} |
+	! -regex '.*(\.svn|work)/.*' -delete -print -maxdepth $depth |
 	sed 's|^./||g')
-if [ "${old_files}" ]; then
+if [ "$old_files" ]; then
 	echo "===> Removed old temporary files"
-	echo ${old_files} | tr ' ' '\n'
+	echo $old_files | tr ' ' '\n'
 fi
-[ ${clean_only} -eq 0 ] || exit
+[ $clean_only -eq 0 ] || exit
 
-if [ ${ignore_empty} -eq 0 ]; then
-	empty_files=$(find . -maxdepth ${depth} -type f -size 0 \
+if [ $ignore_empty -eq 0 ]; then
+	empty_files=$(find . -maxdepth $depth -type f -size 0 \
 			! -regex '.*\.svn/.*' | sed 's|^./||')
-	for file in ${empty_files}; do
-		if ${PSVN} info "${file}" >/dev/null 2>&1; then
-			file_remove "${file}"
+	for file in $empty_files; do
+		if $PSVN info "$file" >/dev/null 2>&1; then
+			file_remove "$file"
 		else
-			rm -f "${file}" &&
-				echo "===> Removed empty untracked file ${file}"
+			rm -f "$file" &&
+				echo "===> Removed empty untracked file $file"
 		fi
 	done
 fi
 
 tempfile=$(mktemp -t ${0##*/})
-if [ ! "${tempfile}" ]; then
+if [ ! "$tempfile" ]; then
 	echo "===> Failed to create temporary file" >&2
 	exit 1
 fi
 trap 'pcommit_exit 1' int
 
-if ! ${PSVN} --show-updates status > ${tempfile}; then
-	echo "===> '${PSVN} status' failed" >&2
+if ! $PSVN --show-updates status > $tempfile; then
+	echo "===> '$PSVN status' failed" >&2
 	pcommit_exit 1
 fi
 
-old_IFS=${IFS}
+old_IFS=$IFS
 IFS=$'\n'
 
-for line in $(cat ${tempfile}); do
-	change=$(echo "${line}" | awk '{
+for line in $(cat $tempfile); do
+	change=$(echo "$line" | awk '{
 		if (match($0, "^Status"))
 			next;
 
@@ -261,33 +261,33 @@ for line in $(cat ${tempfile}); do
 
 		print mod;
 	}')
-	[ "${change}" = " " -o -z "${change}" ] && continue
-	file=$(echo "${line}" | awk '{ print $NF }')
+	[ "$change" = " " -o -z "$change" ] && continue
+	file=$(echo "$line" | awk '{ print $NF }')
 	tracked=0
 
-	case ${change} in
+	case $change in
 	!)
-		file_remove "${file}"
-		[ ${?} -eq 1 ] || tracked=1 ;;
+		file_remove "$file"
+		[ $? -eq 1 ] || tracked=1 ;;
 	N)
-		file_add "${file}"
-		tracked=${?} ;;
+		file_add "$file"
+		tracked=$? ;;
 	U)
-		echo "===> Updating ${file}"
-		${PSVN} -q update "${file}"
+		echo "===> Updating $file"
+		$PSVN -q update "$file"
 	esac
 
-	[ ${tracked} -eq 1 ] || file_set_props "${file}"
+	[ $tracked -eq 1 ] || file_set_props "$file"
 done
 
-rm ${tempfile}
-IFS=${old_IFS}
+rm $tempfile
+IFS=$old_IFS
 
 remove_empty_dirs
 
-if [ ${non_interactive} -eq 1 ]; then
-	${PSVN} commit
-	exit ${?}
+if [ $non_interactive -eq 1 ]; then
+	$PSVN commit
+	exit $?
 fi
 
 while true; do
@@ -295,17 +295,17 @@ while true; do
 	echo -n "> "
 
 	read cmd
-	case ${cmd} in
+	case $cmd in
 	[Cc])
-		${PSVN} commit
-		exit ${?} ;;
+		$PSVN commit
+		exit $? ;;
 	[Qq])
 		exit ;;
 	[Ss])
-		${PSVN} status ;;
+		$PSVN status ;;
 	[Vv])
-		${PSVN} diff | ${PAGER_DIFF} ;;
+		$PSVN diff | $PAGER_DIFF ;;
 	*)
-		echo "===> No such command: ${cmd}"
+		echo "===> No such command: $cmd"
 	esac
 done
diff --git a/pfind b/pfind
--- a/pfind
+++ b/pfind
@@ -19,87 +19,87 @@ EOF
 }
 
 grep_files() {
-	find . -name ${1} -depth ${2} -exec grep -l "${3}" {} \; \
+	find . -name $1 -depth $2 -exec grep -l "$3" {} \; \
 		2>/dev/null | sed 's|^.\/||'
 }
 
 while getopts "b:c:g:hm:n:s:" option; do
-	case ${option} in
+	case $option in
 	b)
-		bdeps="${OPTARG}" ;;
+		bdeps="$OPTARG" ;;
 	c)
-		category="${OPTARG}" ;;
+		category="$OPTARG" ;;
 	g)
-		string="${OPTARG}" ;;
+		string="$OPTARG" ;;
 	m)
-		maintainer="${OPTARG}" ;;
+		maintainer="$OPTARG" ;;
 	n)
-		name="${OPTARG}" ;;
+		name="$OPTARG" ;;
 	s)
-		master="${OPTARG}" ;;
+		master="$OPTARG" ;;
 	*)
 		display_usage
 	esac
 done
 
-[ ! "${bdeps}" -a ! "${category}" -a ! "${maintainer}" -a ! "${name}" \
-	-a ! "${string}" -a ! "${master}" ] && display_usage
+[ ! "$bdeps" -a ! "$category" -a ! "$maintainer" -a ! "$name" \
+	-a ! "$string" -a ! "$master" ] && display_usage
 
 readonly PORTSDIR=${PORTSDIR:-/usr/ports}
-if [ ! -d "${PORTSDIR}" ]; then
-	echo "===> Ports directory not found: ${PORTSDIR}" >&2
+if [ ! -d "$PORTSDIR" ]; then
+	echo "===> Ports directory not found: $PORTSDIR" >&2
 	echo "===> Try setting PORTSDIR enviroment variable" >&2
 	exit 1
 fi
 
-if [ "${category}" -a ! -d ${PORTSDIR}/${category} ]; then
-	echo "===> No such category: ${category}" >&2
+if [ "$category" -a ! -d $PORTSDIR/$category ]; then
+	echo "===> No such category: $category" >&2
 	exit 1
 fi
 
-if [ "${master}" -a ! -d ${PORTSDIR}/${master} ]; then
-	echo "===> No such port: ${PORTSDIR}/${master}" >&2
+if [ "$master" -a ! -d $PORTSDIR/$master ]; then
+	echo "===> No such port: $PORTSDIR/$master" >&2
 	exit 1
 fi
 
-[ ! "${bdeps}" ] || search_args="bdeps=${bdeps}"
-[ ! "${category}" ] || search_args="${search_args} path=${PORTSDIR}/${category}/"
-[ ! "${maintainer}" ] || search_args="${search_args} maint=${maintainer}"
-[ ! "${name}" ] || search_args="${search_args} name=${name}"
-[ "${master}" -a "${search_args}" ] && display_usage
+[ ! "$bdeps" ] || search_args="bdeps=$bdeps"
+[ ! "$category" ] || search_args="$search_args path=$PORTSDIR/$category/"
+[ ! "$maintainer" ] || search_args="$search_args maint=$maintainer"
+[ ! "$name" ] || search_args="$search_args name=$name"
+[ "$master" -a "$search_args" ] && display_usage
 
-cd ${PORTSDIR}
+cd $PORTSDIR
 if [ ! -f "$(make -VINDEXFILE)" ]; then
 	echo "===> Fetching missing index file"
 	make fetchindex || exit 1
 fi
 
-if [ ! "${search_args}" -a ! "${master}" ]; then
-	grep_files Makefile 3 "${string}" | sed 's|\/Makefile$||' | sort
+if [ ! "$search_args" -a ! "$master" ]; then
+	grep_files Makefile 3 "$string" | sed 's|\/Makefile$||' | sort
 	exit
 fi
 
-if [ "${master}" ]; then
-	portdir=$(realpath ${PORTSDIR}/${master})
+if [ "$master" ]; then
+	portdir=$(realpath $PORTSDIR/$master)
 	# search for slaves only in the same category for performance reasons
 	cd ${portdir%/*}
 	candidates=$(for match in $(grep_files "Makefile*" 2 ${portdir##*/}); do
 		[ -d "${match%%/*}" ] || continue
 		[ "${portdir##*/}" = "${match%%/*}" ] || echo ${match%%/*}
 	done | sort -u)
-	portdirs=$(for candidate in ${candidates}; do
+	portdirs=$(for candidate in $candidates; do
 		masterdir=$(realpath `make -C ${candidate%%/*} -V MASTERDIR`)
-		[ "${portdir}" = "${masterdir}" ] && \
-			echo ${PORTSDIR}/${master%/*}/${candidate}
+		[ "$portdir" = "$masterdir" ] && \
+			echo $PORTSDIR/${master%/*}/$candidate
 	done)
 else
-	portdirs=$(make quicksearch ${search_args} | awk '/^Path:/ { print $2 }')
+	portdirs=$(make quicksearch $search_args | awk '/^Path:/ { print $2 }')
 fi
 
-for portdir in ${portdirs}; do
-	if [ "${string}" ]; then
-		[ -e ${portdir}/Makefile ] || continue
-		[ "$(grep "${string}" ${portdir}/Makefile)" ] || continue
+for portdir in $portdirs; do
+	if [ "$string" ]; then
+		[ -e $portdir/Makefile ] || continue
+		[ "$(grep "$string" $portdir/Makefile)" ] || continue
 	fi
-	echo ${portdir} | sed "s|${PORTSDIR}/||"
+	echo $portdir | sed "s|$PORTSDIR/||"
 done
diff --git a/plist-sort b/plist-sort
--- a/plist-sort
+++ b/plist-sort
@@ -3,29 +3,29 @@
 readonly LANG=C
 readonly PKGNAME=$(make -V PKGNAME 2>/dev/null)
 readonly PREFIX=$(make -V PREFIX 2>/dev/null)
-plist_file=${1}
+plist_file=$1
 
-if [ ! "${PKGNAME}" -o ! "${PREFIX}" ]; then
+if [ ! "$PKGNAME" -o ! "$PREFIX" ]; then
 	echo "===> This is not port directory" >&2
 	exit 1
 fi
 
-[ "${plist_file}" ] || plist_file=$(make -V PLIST)
-if [ ! -f "${plist_file}" ]; then
-	echo "===> Plist file was not found: ${plist_file}" >&2
+[ "$plist_file" ] || plist_file=$(make -V PLIST)
+if [ ! -f "$plist_file" ]; then
+	echo "===> Plist file was not found: $plist_file" >&2
 	exit 1
 fi
 
 options_subs="PORTDOCS PORTEXAMPLES"
 for sub in $(make -V PLIST_SUB); do
-	case ${sub} in *@comment*)
-		case ${sub} in NO_*) sub=${sub##NO_}; esac
-		options_subs="${options_subs} ${sub%%=*}"
+	case $sub in *@comment*)
+		case $sub in NO_*) sub=${sub##NO_}; esac
+		options_subs="$options_subs ${sub%%=*}"
 	esac
 done
 
-awk -v prefix="${PREFIX}/" -v plist_subs="$(make -V PLIST_SUB)" \
-	-v options_subs="${options_subs}" '
+awk -v prefix="$PREFIX/" -v plist_subs="$(make -V PLIST_SUB)" \
+	-v options_subs="$options_subs" '
 BEGIN {
 	separator="###";
 
@@ -227,4 +227,4 @@ END {
 
 	for (i in cmds)
 		print cmds[i];
-}' ${plist_file}
+}' $plist_file
diff --git a/plog b/plog
--- a/plog
+++ b/plog
@@ -5,9 +5,9 @@ readonly PAGER=${PAGER:-less}
 readonly POUDRIERE_DIR=${POUDRIERE_DIR:-/usr/local/poudriere}
 readonly POUDRIERE_PORTS=${POUDRIERE_PORTS:-${POUDRIERE_DIR}/ports/default}
 
-cmd=${1}
-port=${2}
-jail=${3}
+cmd=$1
+port=$2
+jail=$3
 
 display_usage() {
 	<< EOF >&2 cat
@@ -24,64 +24,64 @@ poudriere_jails() {
 	poudriere jail -lq | cut -d " " -f1
 }
 
-[ "${cmd}" != "send" -a "${cmd}" != "show" ] && display_usage
+[ "$cmd" != "send" -a "$cmd" != "show" ] && display_usage
 
-if [ ! -d "${POUDRIERE_PORTS}" ]; then
-	echo "===> Ports directory not found: ${POUDRIERE_PORTS}, try setting POUDRIERE_PORTS variable" >&2
+if [ ! -d "$POUDRIERE_PORTS" ]; then
+	echo "===> Ports directory not found: $POUDRIERE_PORTS, try setting POUDRIERE_PORTS variable" >&2
 	exit 1
 fi
 
-[ "${port}" ] || port="."
-if [ "${port}" != "." -a ! -d "${POUDRIERE_PORTS}/${port}" ]; then
-	printf "===> ${POUDRIERE_PORTS}/${port}: no such port found\n\n" >&2
+[ "$port" ] || port="."
+if [ "$port" != "." -a ! -d "$POUDRIERE_PORTS/$port" ]; then
+	printf "===> $POUDRIERE_PORTS/$port: no such port found\n\n" >&2
 	display_usage
 fi
 
-if [ "${jail}" ]; then
-	if [ ! "$(poudriere_jails | grep ${jail})" ]; then
-		printf "===> ${jail}: no such poudriere jail\n\n" >&2
+if [ "$jail" ]; then
+	if [ ! "$(poudriere_jails | grep $jail)" ]; then
+		printf "===> $jail: no such poudriere jail\n\n" >&2
 		display_usage
 	fi
 fi
 
-[ "${port}" = "." ] || cd "${POUDRIERE_PORTS}/${port}"
+[ "$port" = "." ] || cd "$POUDRIERE_PORTS/$port"
 
 readonly PKGBASE=$(make -V PKGBASE 2>/dev/null)
 readonly PKGVERSION=$(make -V PKGVERSION 2>/dev/null)
 
-if [ ! "${PKGBASE}" ]; then
+if [ ! "$PKGBASE" ]; then
 	echo "===> This is not port directory" >&2
 	exit 1
 fi
 
-logdir="${POUDRIERE_DIR}/data/logs/bulk/latest-per-pkg/${PKGBASE}/${PKGVERSION}"
-ports_tree=$(basename "${POUDRIERE_PORTS}")
+logdir="$POUDRIERE_DIR/data/logs/bulk/latest-per-pkg/$PKGBASE/$PKGVERSION"
+ports_tree=$(basename "$POUDRIERE_PORTS")
 
-if [ ! "${jail}" ]; then
+if [ ! "$jail" ]; then
 	for j in $(poudriere_jails | sort -h); do
-		if [ -f "${logdir}/${j}-${ports_tree}.log" ]; then
-			jail="${j}"
+		if [ -f "$logdir/$j-$ports_tree.log" ]; then
+			jail=$j
 			break
 		fi
 	done
 
-	if [ ! "${jail}" ]; then
-		echo "===> Could not find any build logs for ${PKGBASE}-${PKGVERSION}" >&2
+	if [ ! "$jail" ]; then
+		echo "===> Could not find any build logs for $PKGBASE-$PKGVERSION" >&2
 		exit 1
 	fi
 fi
 
-logfile="${logdir}/${jail}-${ports_tree}.log"
-if [ ! -f "${logfile}" ]; then
-	echo "===> Logfile ${logfile} does not exist" >&2
+logfile="$logdir/$jail-$ports_tree.log"
+if [ ! -f "$logfile" ]; then
+	echo "===> Logfile $logfile does not exist" >&2
 	exit 1
 fi
 
-if [ "${cmd}" = "send" ]; then
-	logname="${PKGBASE}-${PKGVERSION}-${jail}.log"
-	echo "===> Uploading to http://people.freebsd.org/~${FREEBSD_LOGIN}/buildlogs/${logname}"
-	scp "${logfile}" ${FREEBSD_LOGIN}@freefall.freebsd.org:public_html/buildlogs/${logname}
+if [ "$cmd" = "send" ]; then
+	logname="$PKGBASE-$PKGVERSION-$jail.log"
+	echo "===> Uploading to http://people.freebsd.org/~$FREEBSD_LOGIN/buildlogs/$logname"
+	scp "$logfile" $FREEBSD_LOGIN@freefall.freebsd.org:public_html/buildlogs/$logname
 else
-	${PAGER} ${logfile}
+	$PAGER $logfile
 fi
 
diff --git a/tbuilder b/tbuilder
--- a/tbuilder
+++ b/tbuilder
@@ -3,8 +3,8 @@
 readonly POUDRIERE_DIR=${POUDRIERE_DIR:-/usr/local/poudriere}
 readonly POUDRIERE_PORTS=${POUDRIERE_PORTS:-${POUDRIERE_DIR}/ports/default}
 
-readonly command=${1}
-query=${2}
+readonly command=$1
+query=$2
 readonly build=${3:-none}
 
 interrupted=0 # build interrupted by ctrl+c
@@ -12,19 +12,19 @@ interrupted=0 # build interrupted by ctrl+c
 check_portname() {
 	local port
 
-	if [ "${1}" = "." ]; then
-		port=$(echo ${PWD} | awk '{
+	if [ "$1" = "." ]; then
+		port=$(echo $PWD | awk '{
 			n = split($0, p ,"/");
 			print p[n-1] "/" p[n];
 		}')
 	else
-		port="${1}"
+		port=$1
 	fi
-	if [ ! -d "${POUDRIERE_PORTS}/${port}" ]; then
-		printf "===> ${POUDRIERE_PORTS}/${port}: port directory does not exists\n\n" >&2
+	if [ ! -d "$POUDRIERE_PORTS/$port" ]; then
+		printf "===> $POUDRIERE_PORTS/$port: port directory does not exists\n\n" >&2
 		display_usage
 	fi
-	echo ${port}
+	echo $port
 }
 
 display_usage() {
@@ -51,13 +51,13 @@ EOF
 }
 
 is_build_dep() {
-	[ "$(make -V BUILD_DEPENDS -V LIB_DEPENDS ${2} \
-		| grep ${1})" ] && return 0 || return 1
+	[ "$(make -V BUILD_DEPENDS -V LIB_DEPENDS $2 \
+		| grep $1)" ] && return 0 || return 1
 }
 
 is_other_dep() {
 	[ "$(make -V FETCH_DEPENDS -V EXTRACT_DEPENDS -V PATCH_DEPENDS \
-		-V RUN_DEPENDS -V TEST_DEPENDS ${2} | grep ${1})" ] &&
+		-V RUN_DEPENDS -V TEST_DEPENDS $2 | grep $1)" ] &&
 		return 0 || return 1
 }
 
@@ -66,40 +66,40 @@ poudriere_jails() {
 }
 
 poudriere_test_build() {
-	local jname=${1} port=${2%%:*} option=${2#*:}
+	local jname=$1 port=${2%%:*} option=${2#*:}
 	local port_cfg outcome="success"
 
-	if [ "${port}" != "${option}" ]; then
+	if [ "$port" != "$option" ]; then
 		if [ "${option%:*}" != "OPT_UNKNOWN"  ]; then
-			echo "*** port ${port} needs ${option%:*} set to ${option#*:} ***"
+			echo "*** port $port needs ${option%:*} set to ${option#*:} ***"
 		else
-			echo "*** port ${port} unknown option needed ***"
+			echo "*** port $port unknown option needed ***"
 		fi
 		port_cfg="-c"
 	fi
 
-	${SUDO} poudriere testport -j ${jname} -o ${port} ${poudriere_args} ${port_cfg}
-	[ ${?} -eq 0 ] || outcome="failed"
-	[ ${interrupted} -eq 0 ] || outcome="interrupted"
-	BUILD_RESULTS="${BUILD_RESULTS} ${port}:${jname}:${outcome}"
+	$SUDO poudriere testport -j $jname -o $port $poudriere_args $port_cfg
+	[ $? -eq 0 ] || outcome="failed"
+	[ $interrupted -eq 0 ] || outcome="interrupted"
+	BUILD_RESULTS="$BUILD_RESULTS $port:$jname:$outcome"
 }
 
-[ "${query}" ] || display_usage
+[ "$query" ] || display_usage
 
-if [ "${build}" != "none" -a "${build}" != "all" \
-	-a -z "$(poudriere_jails | grep ${build})" ]
+if [ "$build" != "none" -a "$build" != "all" \
+	-a -z "$(poudriere_jails | grep $build)" ]
 then
-	printf "===> ${build}: no such poudriere jail\n\n" >&2
+	printf "===> $build: no such poudriere jail\n\n" >&2
 	display_usage
 fi
 
-if [ "${4}" ]; then
+if [ "$4" ]; then
 	shift 3;
-	poudriere_args="${*}";
+	poudriere_args="$*";
 fi
 
-if [ ! -d "${POUDRIERE_PORTS}" ]; then
-	echo "===> Poudriere ports directory not found: ${POUDRIERE_PORTS}" >&2
+if [ ! -d "$POUDRIERE_PORTS" ]; then
+	echo "===> Poudriere ports directory not found: $POUDRIERE_PORTS" >&2
 	echo "===> Try setting POUDRIERE_PORTS enviroment variable" >&2
 	exit 1
 fi
@@ -114,70 +114,70 @@ fi
 
 trap 'interrupted=1' int
 
-case ${command} in
+case $command in
 bdeps)
-	ports=$(pfind -b ${query}) ;;
+	ports=$(pfind -b $query) ;;
 file)
-	if [ ! -f "${query}" ]; then
-		echo "===> File ${query} does not exists" >&2
+	if [ ! -f "$query" ]; then
+		echo "===> File $query does not exists" >&2
 		exit 1
 	fi
-	ports=$(cat "${query}" | grep -v '^#') ;;
+	ports=$(cat "$query" | grep -v '^#') ;;
 grep)
-	ports=$(cd ${POUDRIERE_PORTS} && find . -name "Makefile*" -exec \
-		grep -q "${query}" {} \; -print | grep -v "${query}/Makefile" |
+	ports=$(cd $POUDRIERE_PORTS && find . -name "Makefile*" -exec \
+		grep -q "$query" {} \; -print | grep -v "$query/Makefile" |
 		sed -E 's;(\./|/Makefile);;g') ;;
 ldeps)
-	query=$(check_portname ${query})
-	tmp=$(cd ${POUDRIERE_PORTS} && find . -name "Makefile*" -exec grep -q \
-		"^[^#].*${query}[ \\]*\$" {} \; -print | sed 's|\./||')
+	query=$(check_portname $query)
+	tmp=$(cd $POUDRIERE_PORTS && find . -name "Makefile*" -exec grep -q \
+		"^[^#].*$query[ \\]*\$" {} \; -print | sed 's|\./||')
 
-	for path in ${tmp}; do
-		path=$(dirname ${path})
-		[ "${query}" != "${path}" ] || continue
-		cd ${POUDRIERE_PORTS}/${path}
-		if is_build_dep ${query}; then
-			ports="${ports} ${path}"
+	for path in $tmp; do
+		path=$(dirname $path)
+		[ "$query" != "$path" ] || continue
+		cd $POUDRIERE_PORTS/$path
+		if is_build_dep $query; then
+			ports="$ports $path"
 			continue
 		fi
-		is_other_dep ${query} && continue
+		is_other_dep $query && continue
 
 		for option in $(make pretty-print-config); do
-			case ${option} in -*)
-				if is_build_dep ${query} OPTIONS_DEFAULT=${option#-}; then
-					ports="${ports} ${path}:${option#-}:on"
+			case $option in -*)
+				if is_build_dep $query OPTIONS_DEFAULT=${option#-}; then
+					ports="$ports $path:${option#-}:on"
 					continue 2
 				fi
-				is_other_dep ${query} OPTIONS_DEFAULT=${option#-} && continue 2
+				is_other_dep $query OPTIONS_DEFAULT=${option#-} && continue 2
 			esac
 		done
 		for option in $(make pretty-print-config); do
-			case ${option} in +*)
-				if is_build_dep ${query} OPTIONS_UNSET=${option#+}; then
-					ports="${ports} ${path}:${option#+}:off"
+			case $option in +*)
+				if is_build_dep $query OPTIONS_UNSET=${option#+}; then
+					ports="$ports $path:${option#+}:off"
 					continue 2
 				fi
 			esac
 		done
-		ports="${ports} ${path}:OPT_UNKNOWN:none"
+		ports="$ports $path:OPT_UNKNOWN:none"
 	done
 	;;
 match)
-	ports=$(pfind -n ${query}) ;;
+	ports=$(pfind -n $query) ;;
 name)
-	ports=$(check_portname ${query}) ;;
+	ports=$(check_portname $query) ;;
 slaves)
-	master=$(check_portname ${query})
-	ports=$(pfind -s ${master}) ;;
+	master=$(check_portname $query)
+	ports=$(pfind -s $master) ;;
 *)
 	display_usage
 esac
 
-for port in ${ports}; do
-	case ${build} in
+for port in $ports; do
+	case $build in
 	none)
 		option=${port#*:}
-		if [ "${command}" != "name" ]; then
+		if [ "$command" != "name" ]; then
 			case ${option%:*} in
 			"${port%%:*}")
 				echo "Found match: ${port%%:*}" ;;
@@ -190,20 +190,20 @@ for port in ${ports}; do
 		;;
 	all)
 		for b in $(poudriere_jails | sort -h); do
-			poudriere_test_build ${b} ${port}
-			[ ${interrupted} -eq 0 ] || break 2
+			poudriere_test_build $b $port
+			[ $interrupted -eq 0 ] || break 2
 		done ;;
 	*)
-		poudriere_test_build ${build} ${port}
-		[ ${interrupted} -eq 0 ] || break
+		poudriere_test_build $build $port
+		[ $interrupted -eq 0 ] || break
 	esac
 done
 
-if [ "${BUILD_RESULTS}" ]; then
+if [ "$BUILD_RESULTS" ]; then
 	printf "\n===> Following build(s) were performed:\n"
 	printf "%-40s %-15s %s\n" "PORTNAME" "JAIL" "RESULT"
 
-	for result in ${BUILD_RESULTS}; do
+	for result in $BUILD_RESULTS; do
 		params=${result#*:}
 		printf "%-40s %-15s %s\n" "${result%%:*}" \
 			${params%:*} ${params#*:}
diff --git a/upgrade-base b/upgrade-base
--- a/upgrade-base
+++ b/upgrade-base
@@ -4,7 +4,7 @@ readonly MAKE=${MAKE:-make}
 readonly PSVN=${PSVN:-svn}
 readonly SRCDIR=${SRCDIR:-/usr/src}
 readonly XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
-readonly CONF_FILE="${XDG_CONFIG_HOME}/upgrade-base"
+readonly CONF_FILE="$XDG_CONFIG_HOME/upgrade-base"
 
 readonly tcols=$(stty size | cut -d" " -f2)
 readonly tlines=$(stty size | cut -d" " -f1)
@@ -17,12 +17,12 @@ ask_yesno() {
 	local answer
 
 	while true; do
-		echo -n "${1} (y/n)? [y] "
+		echo -n "$1 (y/n)? [y] "
 
 		read answer
-		[ "${answer}" ] || answer="y"
+		[ "$answer" ] || answer="y"
 
-		case ${answer} in
+		case $answer in
 		[Nn])
 			return 1 ;;
 		[Yy])
@@ -34,26 +34,26 @@ ask_yesno() {
 delete_old_files() {
 	local file items tmpfile=$(mktemp -t ${0##*/}) to_remove tstr type
 
-	[ "${tmpfile}" ] || return
+	[ "$tmpfile" ] || return
 
 	for type in libs files dirs; do
-		${MAKE} check-old-${type} | grep '^/' > ${tmpfile}
+		$MAKE check-old-$type | grep '^/' > $tmpfile
 		tstr=$(echo $type | cut -b1)
-		for file in $(cat ${tmpfile}); do
-			items="${items} \"${file}\" ${tstr} on"
+		for file in $(cat $tmpfile); do
+			items="$items \"$file\" $tstr on"
 		done
 	done
-	if [ "${items}" ]; then
+	if [ "$items" ]; then
 		echo "--stdout --checklist \"Choose old files to delete\" \
-			$((tlines-3)) ${dwidth} $((tlines-5)) \
-			${items}" > ${tmpfile}
-		to_remove=$(dialog --file ${tmpfile})
+			$((tlines-3)) $dwidth $((tlines-5)) \
+			$items" > $tmpfile
+		to_remove=$(dialog --file $tmpfile)
 		dialog --clear
-		for file in ${to_remove}; do
-			rm -rf ${file}
+		for file in $to_remove; do
+			rm -rf $file
 		done
 	fi
-	rm ${tmpfile}
+	rm $tmpfile
 }
 
 display_usage() {
@@ -70,44 +70,44 @@ EOF
 # $1 make target
 # $2 state status afterwards
 exec_cmd() {
-	if ! ${1}; then
-		echo "===> '${1}' failed" >&2
+	if ! $1; then
+		echo "===> '$1' failed" >&2
 		exit 1
 	fi
-	save_state "${2}"
+	save_state "$2"
 }
 
 last_updating_entry() {
-	if [ -f "${SRCDIR}/UPDATING" ]; then
-		egrep -m 1 '^[0-9]{8}\:' ${SRCDIR}/UPDATING | sed 's|:||'
+	if [ -f "$SRCDIR/UPDATING" ]; then
+		egrep -m 1 '^[0-9]{8}\:' $SRCDIR/UPDATING | sed 's|:||'
 	else
 		echo "0"
 	fi
 }
 
 main_loop() {
-	local l_entry n_entry state=$(cat ${CONF_FILE} 2>/dev/null)
+	local l_entry n_entry state=$(cat $CONF_FILE 2>/dev/null)
 
-	case ${state} in
+	case $state in
 	"")
-		if [ ${skip_tree_update} -eq 0 ]; then
+		if [ $skip_tree_update -eq 0 ]; then
 			l_entry=$(last_updating_entry)
-			if ! ${PSVN} update; then
+			if ! $PSVN update; then
 				echo "===> Updating of source tree failed" >&2
 				exit 1
 			fi
 
 			n_entry=$(last_updating_entry)
-			if [ ${n_entry} -gt ${l_entry} ]; then
-				printf "===> New entries since last upgrade in ${SRCDIR}/UPDATING file:\n\n"
-				awk -F ':' -v entry="${l_entry}" '
+			if [ $n_entry -gt $l_entry ]; then
+				printf "===> New entries since last upgrade in $SRCDIR/UPDATING file:\n\n"
+				awk -F ':' -v entry="$l_entry" '
 				/^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]:/ {
 					if (entry == $1)
 						exit;
 					else
 						new_entry=1;
 				}
-				new_entry { print $0 }' ${SRCDIR}/UPDATING
+				new_entry { print $0 }' $SRCDIR/UPDATING
 
 				if ! ask_yesno "Continue with upgrade"; then
 					save_state "REPO_UPDATED"
@@ -118,17 +118,17 @@ main_loop() {
 
 		save_state "REPO_UPDATED" ;;
 	"REPO_UPDATED")
-		exec_cmd "${MAKE} buildworld ${make_args}" "WORLD_BUILT" ;;
+		exec_cmd "$MAKE buildworld $make_args" "WORLD_BUILT" ;;
 	"WORLD_BUILT")
-		exec_cmd "${MAKE} buildkernel ${make_args}" "KERNEL_BUILT" ;;
+		exec_cmd "$MAKE buildkernel $make_args" "KERNEL_BUILT" ;;
 	"KERNEL_BUILT")
-		exec_cmd "${MAKE} installkernel ${make_args}" "KERNEL_INSTALLED"
+		exec_cmd "$MAKE installkernel $make_args" "KERNEL_INSTALLED"
 		printf "\n===> You need to restart computer now.\n\n"
 		exit 0 ;;
 	"KERNEL_INSTALLED")
 		exec_cmd "mergemaster -p" "MERGEMASTER_INIT"  ;;
 	"MERGEMASTER_INIT")
-		exec_cmd "${MAKE} installworld ${make_args}" "WORLD_INSTALLED" ;;
+		exec_cmd "$MAKE installworld $make_args" "WORLD_INSTALLED" ;;
 	"WORLD_INSTALLED")
 		exec_cmd "mergemaster -Fui" "MERGEMASTER_DONE" ;;
 	"MERGEMASTER_DONE")
@@ -140,7 +140,7 @@ main_loop() {
 		printf "\n===> You need to restart computer again.\n\n"
 		exit 0 ;;
 	*)
-		echo "===> Garbage in ${CONF_FILE}, try upgrade-base -s" >&2
+		echo "===> Garbage in $CONF_FILE, try upgrade-base -s" >&2
 		exit 1
 	esac
 	main_loop
@@ -148,14 +148,14 @@ main_loop() {
 
 # $1 state
 save_state() {
-	[ -d "${XDG_CONFIG_HOME}" ] || mkdir "${XDG_CONFIG_HOME}"
-	echo "${1}" > ${CONF_FILE}
+	[ -d "$XDG_CONFIG_HOME" ] || mkdir "$XDG_CONFIG_HOME"
+	echo "$1" > $CONF_FILE
 }
 
 while getopts "hsu" option; do
-	case ${option} in
+	case $option in
 	s)
-		echo > "${CONF_FILE}" ;;
+		echo > "$CONF_FILE" ;;
 	u)
 		skip_tree_update=1 ;;
 	*)
@@ -169,18 +169,18 @@ if [ $(id -u) -ne 0 ]; then
 fi
 
 jobs=$(sysctl -n hw.ncpu)
-[ "${jobs}" ] && make_args="${make_args} -j${jobs}"
+[ "$jobs" ] && make_args="$make_args -j$jobs"
 
 ports_modules=$(pkg which -qo /boot/modules/* | sort -u | tr '\n' ' ')
-if [ "${ports_modules}" ]; then
+if [ "$ports_modules" ]; then
 	readonly PORTSDIR=${PORTSDIR:-/usr/ports}
-	if [ ! -d "${PORTSDIR}" ]; then
-		echo "===> Ports directory not found: ${PORTSDIR}" >&2
+	if [ ! -d "$PORTSDIR" ]; then
+		echo "===> Ports directory not found: $PORTSDIR" >&2
 		echo "===> Try setting PORTSDIR enviroment variable" >&2
 		exit 1
 	fi
-	make_args="${make_args} PORTSDIR=${PORTSDIR}"
-	export PORTS_MODULES="${ports_modules}"
+	make_args="$make_args PORTSDIR=$PORTSDIR"
+	export PORTS_MODULES="$ports_modules"
 fi
-cd ${SRCDIR}
+cd $SRCDIR
 main_loop
