Don't try to guess PORTSDIR pathname, if it's not there just fail

diff --git a/pdiff b/pdiff
--- a/pdiff
+++ b/pdiff
@@ -1,10 +1,9 @@
 #!/bin/sh
 
-PORTSDIR="${PORTSDIR:-/usr/ports}"
-[ -d "${PORTSDIR}" ] ||
-	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
-if [ ! -d "${PORTSDIR}" ]; then
-	echo "===> Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
+readonly PORTSDIR=${PORTSDIR:-/usr/ports}
+if [ -d "${PORTSDIR}" ]; then
+	echo "===> Ports directory not found: ${PORTSDIR}" >&2
+	echo "===> Try setting PORTSDIR enviroment variable" >&2
 	exit 1
 fi
 
diff --git a/pfind b/pfind
--- a/pfind
+++ b/pfind
@@ -1,6 +1,11 @@
 #!/bin/sh
 
-PORTSDIR=${PORTSDIR:-/usr/ports}
+readonly PORTSDIR=${PORTSDIR:-/usr/ports}
+if [ -d "${PORTSDIR}" ]; then
+	echo "===> Ports directory not found: ${PORTSDIR}" >&2
+	echo "===> Try setting PORTSDIR enviroment variable" >&2
+	exit 1
+fi
 
 display_usage() {
 	<< EOF >&2 cat
@@ -47,12 +52,6 @@ done
 [ ! "${bdeps}" -a ! "${category}" -a ! "${maintainer}" -a ! "${name}" \
 	-a ! "${string}" -a ! "${master}" ] && display_usage
 
-[ -d "${PORTSDIR}" ] || \
-	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
-if [ ! -d "${PORTSDIR}" ]; then
-	echo "===> Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
-	exit 1
-fi
 
 if [ "${category}" -a ! -d ${PORTSDIR}/${category} ]; then
 	echo "===> No such category: ${category}" >&2
diff --git a/upgrade-base b/upgrade-base
--- a/upgrade-base
+++ b/upgrade-base
@@ -5,6 +5,14 @@ readonly PSVN=${PSVN:-svn}
 readonly SRCDIR=${SRCDIR:-/usr/src}
 readonly XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
 readonly CONF_FILE="${XDG_CONFIG_HOME}/upgrade-base"
+# needed for rebuilding kernel modules ports
+readonly PORTSDIR=${PORTSDIR:-/usr/ports}
+if [ -d "${PORTSDIR}" ]; then
+	echo "===> Ports directory not found: ${PORTSDIR}" >&2
+	echo "===> Try setting PORTSDIR enviroment variable" >&2
+	exit 1
+fi
+
 readonly tcols=$(stty size | cut -d" " -f2)
 readonly tlines=$(stty size | cut -d" " -f1)
 
@@ -166,15 +174,6 @@ fi
 
 jobs="$(sysctl -n hw.ncpu)"
 [ "${jobs}" ] && make_args="${make_args} -j${jobs}"
-
-# needed for rebuilding kernel modules ports
-PORTSDIR=${PORTSDIR:-/usr/ports}
-[ -d "${PORTSDIR}" ] ||
-	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
-if [ ! -d "${PORTSDIR}" ]; then
-	echo "===> Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
-	exit 1
-fi
 make_args="${make_args} PORTSDIR=${PORTSDIR}"
 
 ports_modules="$(pkg which -qo /boot/modules/* | uniq | tr '\n' ' ')"
diff --git a/upgrade-ports b/upgrade-ports
--- a/upgrade-ports
+++ b/upgrade-ports
@@ -2,7 +2,12 @@
 
 readonly XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
 readonly CONFIG="${XDG_CONFIG_HOME}/upgrade-ports"
-export readonly PORTSDIR=${PORTSDIR:-/usr/ports}
+readonly PORTSDIR=${PORTSDIR:-/usr/ports}
+if [ -d "${PORTSDIR}" ]; then
+	echo "===> Ports directory not found: ${PORTSDIR}" >&2
+	echo "===> Try setting PORTSDIR enviroment variable" >&2
+	exit 1
+fi
 
 answer_yes=0	# answer yes to all of the questions
 skip_update=0	# don't update ports tree
