Check if PORTSDIR exists, try to configure it if not

diff --git a/pdiff b/pdiff
--- a/pdiff
+++ b/pdiff
@@ -1,6 +1,13 @@
 #!/bin/sh
 
-readonly PORTSDIR="${PORTSDIR:-/usr/ports}"
+PORTSDIR="${PORTSDIR:-/usr/ports}"
+[ -d "${PORTSDIR}" ] || \
+	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
+if [ ! -d "${PORTSDIR}" ]; then
+	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable"
+	exit 1
+fi
+
 readonly base_dir="${PWD}"
 readonly category="$(make -V CATEGORIES | awk '{print $1}')"
 readonly port="$(basename ${PWD})"
diff --git a/pfind b/pfind
--- a/pfind
+++ b/pfind
@@ -1,6 +1,12 @@
 #!/bin/sh
 
-readonly PORTSDIR=${PORTSDIR:-/usr/ports}
+PORTSDIR=${PORTSDIR:-/usr/ports}
+[ -d "${PORTSDIR}" ] || \
+	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
+if [ ! -d "${PORTSDIR}" ]; then
+	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable"
+	exit 1
+fi
 
 display_usage() {
 	echo "Usage: pfind [-c category] [-h] [-m maintainer] [-n name] [-s string]"
diff --git a/upgrade-ports b/upgrade-ports
--- a/upgrade-ports
+++ b/upgrade-ports
@@ -4,7 +4,14 @@ readonly XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
 readonly CONFIG="${XDG_CONFIG_HOME}/upgrade-ports"
 readonly PAGER="${PAGER:-less}"
 readonly PATH="${PATH}:/usr/local/sbin"
-readonly PORTSDIR="${PORTSDIR:-/usr/ports}"
+
+PORTSDIR=${PORTSDIR:-/usr/ports}
+[ -d "${PORTSDIR}" ] || \
+	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
+if [ ! -d "${PORTSDIR}" ]; then
+	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable"
+	exit 1
+fi
 
 answer_yes=0
 wait_for_key=0
