Use sudo for fetchig index if user don't have right privileges

diff --git a/pfind b/pfind
--- a/pfind
+++ b/pfind
@@ -113,8 +113,16 @@ fi
 cd "$PORTSDIR"
 indexfile=$(make -V INDEXFILE)
 if [ ! -f "$indexfile" ]; then
+	if [ $(id -u) -ne 0 ]; then
+		if ! which sudo >/dev/null; then
+			echo "===> sudo not found" >&2
+			echo "===> root privileges or properly configured sudo required for fetching ports INDEX file." >&2
+			exit 1
+		fi
+		SUDO="sudo"
+	fi
 	echo "===> Fetching missing index file..."
-	if ! make fetchindex; then
+	if ! $SUDO make fetchindex; then
 		echo "===> Could not fetch index file" >&2
 		exit 1
 	fi
