First parse command line args then check enviroment for needed things

diff --git a/pfind b/pfind
--- a/pfind
+++ b/pfind
@@ -1,12 +1,6 @@
 #!/bin/sh
 
 PORTSDIR=${PORTSDIR:-/usr/ports}
-[ -d "${PORTSDIR}" ] || \
-	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
-if [ ! -d "${PORTSDIR}" ]; then
-	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
-	exit 1
-fi
 
 display_usage() {
 	<< EOF >&2 cat
@@ -25,11 +19,7 @@ EOF
 while getopts "c:hm:n:s:" option; do
 	case ${option} in
 	c)
-		if [ ! -d ${PORTSDIR}/${OPTARG} ]; then
-			echo "No such category: ${OPTARG}" >&2
-			exit 1
-		fi
-		category="${OPTARG}/" ;;
+		category="${OPTARG}" ;;
 	m)
 		maintainer="${OPTARG}" ;;
 	n)
@@ -44,7 +34,19 @@ done
 [ -z "${category}" -a -z "${maintainer}" -a -z "${name}" -a -z "${string}" ] && \
 	display_usage
 
-[ -z "${category}" ] || search_args="path=${PORTSDIR}/${category}"
+[ -d "${PORTSDIR}" ] || \
+	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
+if [ ! -d "${PORTSDIR}" ]; then
+	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
+	exit 1
+fi
+
+if [ -n "${category}" -a ! -d ${PORTSDIR}/${category} ]; then
+	echo "No such category: ${category}" >&2
+	exit 1
+fi
+
+[ -z "${category}" ] || search_args="path=${PORTSDIR}/${category}/"
 [ -z "${maintainer}" ] || search_args="${search_args} maint=${maintainer}"
 [ -z "${name}" ] || search_args="${search_args} name=${name}"
 
diff --git a/plog b/plog
--- a/plog
+++ b/plog
@@ -5,11 +5,6 @@ readonly PAGER="${PAGER:-less}"
 readonly POUDRIERE_DIR="${POUDRIERE_DIR:-/usr/local/poudriere}"
 readonly POUDRIERE_PORTS="${POUDRIERE_PORTS:-${POUDRIERE_DIR}/ports/default}"
 
-if [ ! -d "${POUDRIERE_PORTS}" ]; then
-	echo "Ports directory not found: ${POUDRIERE_PORTS}, try setting POUDRIERE_PORTS variable" >&2
-	exit 1
-fi
-
 cmd="${1}"
 port="${2}"
 jail="${3}"
@@ -30,6 +25,11 @@ poudriere_jails() {
 }
 
 [ "${cmd}" != "send" -a "${cmd}" != "show" ] && display_usage
+
+if [ ! -d "${POUDRIERE_PORTS}" ]; then
+	echo "Ports directory not found: ${POUDRIERE_PORTS}, try setting POUDRIERE_PORTS variable" >&2
+	exit 1
+fi
 
 [ -n "${port}" ] || port="."
 if [ "${port}" != "." -a ! -d "${POUDRIERE_PORTS}/${port}" ]; then
diff --git a/tbuilder b/tbuilder
--- a/tbuilder
+++ b/tbuilder
@@ -5,11 +5,6 @@ readonly PATH="${PATH}:${PORTSDIR}/Tools/scripts"
 readonly POUDRIERE_DIR="${POUDRIERE_DIR:-/usr/local/poudriere}"
 readonly POUDRIERE_PORTS="${POUDRIERE_PORTS:-${POUDRIERE_DIR}/ports/default}"
 
-if [ ! -d "${POUDRIERE_PORTS}" ]; then
-	echo "Ports directory not found: ${POUDRIERE_PORTS}, try setting POUDRIERE_PORTS variable" >&2
-	exit 1
-fi
-
 readonly command="${1}"
 readonly query="${2}"
 readonly build="${3:-none}"
@@ -74,6 +69,11 @@ fi
 if [ -n "${4}" ]; then
 	shift 3;
 	poudriere_args="${*}";
+fi
+
+if [ ! -d "${POUDRIERE_PORTS}" ]; then
+	echo "Ports directory not found: ${POUDRIERE_PORTS}, try setting POUDRIERE_PORTS variable" >&2
+	exit 1
 fi
 
 if [ $(id -u) -ne 0 ]; then
diff --git a/upgrade-ports b/upgrade-ports
--- a/upgrade-ports
+++ b/upgrade-ports
@@ -5,12 +5,6 @@ readonly CONFIG="${XDG_CONFIG_HOME}/upgrade-ports"
 readonly PAGER="${PAGER:-less}"
 
 PORTSDIR=${PORTSDIR:-/usr/ports}
-[ -d "${PORTSDIR}" ] || \
-	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
-if [ ! -d "${PORTSDIR}" ]; then
-	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
-	exit 1
-fi
 
 answer_yes=0
 wait_for_key=0
@@ -214,6 +208,13 @@ while getopts "hwy" option; do
 		display_usage
 	esac
 done
+
+[ -d "${PORTSDIR}" ] || \
+	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
+if [ ! -d "${PORTSDIR}" ]; then
+	echo "Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
+	exit 1
+fi
 
 if [ $(id -u) -ne 0 ]; then
 	which sudo >/dev/null
