Fix messy PORTSDIR handling, part 2

diff --git a/pfind b/pfind
--- a/pfind
+++ b/pfind
@@ -1,12 +1,5 @@
 #!/bin/sh
 
-readonly PORTSDIR=${PORTSDIR:-/usr/ports}
-if [ -d "${PORTSDIR}" ]; then
-	echo "===> Ports directory not found: ${PORTSDIR}" >&2
-	echo "===> Try setting PORTSDIR enviroment variable" >&2
-	exit 1
-fi
-
 display_usage() {
 	<< EOF >&2 cat
 Usage: ${0##*/} [-h]
@@ -52,6 +45,12 @@ done
 [ ! "${bdeps}" -a ! "${category}" -a ! "${maintainer}" -a ! "${name}" \
 	-a ! "${string}" -a ! "${master}" ] && display_usage
 
+readonly PORTSDIR=${PORTSDIR:-/usr/ports}
+if [ -d "${PORTSDIR}" ]; then
+	echo "===> Ports directory not found: ${PORTSDIR}" >&2
+	echo "===> Try setting PORTSDIR enviroment variable" >&2
+	exit 1
+fi
 
 if [ "${category}" -a ! -d ${PORTSDIR}/${category} ]; then
 	echo "===> No such category: ${category}" >&2
diff --git a/upgrade-ports b/upgrade-ports
--- a/upgrade-ports
+++ b/upgrade-ports
@@ -2,12 +2,7 @@
 
 readonly XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
 readonly CONFIG="${XDG_CONFIG_HOME}/upgrade-ports"
-readonly PORTSDIR=${PORTSDIR:-/usr/ports}
-if [ -d "${PORTSDIR}" ]; then
-	echo "===> Ports directory not found: ${PORTSDIR}" >&2
-	echo "===> Try setting PORTSDIR enviroment variable" >&2
-	exit 1
-fi
+export readonly PORTSDIR=${PORTSDIR:-/usr/ports}
 
 answer_yes=0	# answer yes to all of the questions
 skip_update=0	# don't update ports tree
@@ -319,10 +314,9 @@ while getopts "huwy" option; do
 	esac
 done
 
-[ -d "${PORTSDIR}" ] ||
-	PORTSDIR="$(make -V PORTSDIR /usr/share/mk/bsd.ports.mk 2>/dev/null)"
-if [ ! -d "${PORTSDIR}" ]; then
-	echo "===> Ports directory not found: ${PORTSDIR}, try setting PORTSDIR variable" >&2
+if [ -d "${PORTSDIR}" ]; then
+	echo "===> Ports directory not found: ${PORTSDIR}" >&2
+	echo "===> Try setting PORTSDIR enviroment variable" >&2
 	exit 1
 fi
 
