Make poudriere ports error message more clear and same as in tbuilder

diff --git a/plog b/plog
--- a/plog
+++ b/plog
@@ -27,7 +27,8 @@ poudriere_jails() {
 [ "$cmd" != "send" -a "$cmd" != "show" ] && display_usage
 
 if [ ! -d "$POUDRIERE_PORTS" ]; then
-	echo "===> Ports directory not found: $POUDRIERE_PORTS, try setting POUDRIERE_PORTS variable" >&2
+	echo "===> Poudriere ports directory not found: $POUDRIERE_PORTS" >&2
+	echo "===> Try setting POUDRIERE_PORTS enviroment variable" >&2
 	exit 1
 fi
 
