Try to use sudo only when UID != 0

diff --git a/tbuilder b/tbuilder
--- a/tbuilder
+++ b/tbuilder
@@ -54,7 +54,7 @@ poudriere_test_build() {
 		fi
 	fi
 
-	sudo poudriere testport -j ${jname} -o ${port} ${poudriere_args} ${port_cfg}
+	${SUDO} poudriere testport -j ${jname} -o ${port} ${poudriere_args} ${port_cfg}
 	if [ ${?} -ne 0 ]; then
 		BUILD_RESULTS="${BUILD_RESULTS} ${port}:${jname}:failed"
 	else
@@ -74,6 +74,16 @@ fi
 if [ -n "${4}" ]; then
 	shift 3;
 	poudriere_args="${*}";
+fi
+
+if [ $(id -u) -ne 0 ]; then
+	if [ -z "$(whereis -bq sudo)" ]; then
+		echo "===> sudo not found" >&2
+		exit 1
+	fi
+	SUDO="sudo"
+else
+	SUDO=""
 fi
 
 case ${command} in
diff --git a/upgrade-ports b/upgrade-ports
--- a/upgrade-ports
+++ b/upgrade-ports
@@ -189,10 +189,14 @@ while getopts "hwy" option; do
 	esac
 done
 
-
-if [ -z "$(whereis -bq sudo)" ]; then
-	echo "===> sudo not found" >&2
-	upgrade_exit 1 "" ${wait_for_key}
+if [ $(id -u) -ne 0 ]; then
+	if [ -z "$(whereis -bq sudo)" ]; then
+		echo "===> sudo not found" >&2
+		upgrade_exit 1 "" ${wait_for_key}
+	fi
+	SUDO="sudo"
+else
+	SUDO=""
 fi
 
 if [ -z "$(whereis -bq portmaster)" ]; then
@@ -214,7 +218,7 @@ fi
 
 [ -n "${last_read}" ] || last_read="$(get_entry_dates | head -n 1)"
 
-sudo /usr/sbin/portsnap fetch update
+${SUDO} /usr/sbin/portsnap fetch update
 if [ ${?} -ne 0 ]; then
 	echo "===> Ports tree update failed" >&2
 	upgrade_exit 1 "" ${wait_for_key}
@@ -246,7 +250,7 @@ if [ ${last_read} -lt ${last_upd} ]; then
 
 			if ask_yesno "Run '${cmd}'"; then
 				IFS=${old_IFS}
-				sudo ${cmd}
+				${SUDO} ${cmd}
 				ret=${?}
 				IFS=$'\n'
 				
@@ -266,5 +270,5 @@ if [ ${last_read} -lt ${last_upd} ]; then
 	fi	
 fi
 
-sudo portmaster -a ${portmaster_args}
+${SUDO} portmaster -a ${portmaster_args}
 upgrade_exit ${?} "${last_upd}" ${wait_for_key}
