Only check PORTSDIR when there are ports with kernel modules to rebuild

diff --git a/upgrade-base b/upgrade-base
--- a/upgrade-base
+++ b/upgrade-base
@@ -168,17 +168,16 @@ fi
 jobs="$(sysctl -n hw.ncpu)"
 [ "${jobs}" ] && make_args="${make_args} -j${jobs}"
 
-# needed for rebuilding kernel modules ports
-readonly PORTSDIR=${PORTSDIR:-/usr/ports}
-if [ ! -d "${PORTSDIR}" ]; then
-	echo "===> Ports directory not found: ${PORTSDIR}" >&2
-	echo "===> Try setting PORTSDIR enviroment variable" >&2
-	exit 1
+ports_modules="$(pkg which -qo /boot/modules/* | sort -u | tr '\n' ' ')"
+if [ "${ports_modules}" ]; then
+	readonly PORTSDIR=${PORTSDIR:-/usr/ports}
+	if [ ! -d "${PORTSDIR}" ]; then
+		echo "===> Ports directory not found: ${PORTSDIR}" >&2
+		echo "===> Try setting PORTSDIR enviroment variable" >&2
+		exit 1
+	fi
+	make_args="${make_args} PORTSDIR=${PORTSDIR}"
+	export PORTS_MODULES="${ports_modules}"
 fi
-make_args="${make_args} PORTSDIR=${PORTSDIR}"
-
-ports_modules="$(pkg which -qo /boot/modules/* | uniq | tr '\n' ' ')"
-[ "${ports_modules}" ] && export PORTS_MODULES="${ports_modules}"
-
 cd ${SRCDIR}
 main_loop
